version: '3.9'
services:
  
  client:
    env_file: ./client/.env.dev
    image: freelance_form_client-dev
    container_name: freelance_form_client-dev
    build:
      context: ./client/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client/src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - server
    
  server:
    env_file: ./server/.env.dev
    image: freelance_form_server-dev
    container_name: freelance_form_server-dev
    build:
      context: ./server/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - '8080:8080'